In [6]:
import os
import numpy as np
from typhon.arts.workspace import Workspace, arts_agenda
from typhon.arts import sensor, xml
from typhon.physics import wavelength2frequency, wavenumber2frequency

In [7]:
ws = Workspace(verbosity = 1)

eresma_atm = xml.load("/scratch/uni/u237/user_data/mprange/arts-xml-data/planets/Earth/ECMWF/"
                  "IFS/Eresmaa_137L/eresmaal137_all_q.xml.gz")
eresma_sfc = xml.load("/scratch/uni/u237/user_data/mprange/arts-xml-data/planets/Earth/ECMWF/"
                  "IFS/Eresmaa_137L/eresmaal137_all_q_surface.xml.gz")
garand = xml.load("/scratch/uni/u237/users/mprange/arts/controlfiles/testdata/garand_profiles.xml.gz")
iasi_obs = xml.load("/scratch/uni/u237/users/mprange/phd/iasi_retrieval/iasi_obs_simulation/"
                    "eresmaa_iasi_obs_119000_140000_225000_240000_cm-1/"
                    "iasi_obs.xml")

In [12]:
eresma_sfc

array([[ 5.00100e+03,  1.15029e+01,  1.31392e+03, ...,  2.71460e+02,
         2.71460e+02,  2.71460e+02],
       [ 5.00200e+03,  1.14828e+01,  2.92992e+03, ...,  2.71460e+02,
         2.71460e+02,  2.71460e+02],
       [ 5.00300e+03,  1.14681e+01,  4.51192e+03, ...,  2.71460e+02,
         2.71460e+02,  2.71460e+02],
       ...,
       [ 9.99800e+03,  1.15112e+01,  1.91968e+00, ...,  2.71460e+02,
         2.71460e+02,  2.71460e+02],
       [ 9.99900e+03,  1.15378e+01, -2.08032e+00, ...,  2.71460e+02,
         2.71460e+02,  2.71460e+02],
       [ 1.00000e+04,  1.15286e+01,  1.91968e+00, ...,  2.71460e+02,
         2.71460e+02,  2.71460e+02]])

In [35]:
iasi_obs

[array([279.39818048, 278.55660605, 278.71668151, ..., 271.04691869,
        271.26330856, 271.4542948 ]),
 array([283.01531019, 282.23005694, 282.3936781 , ..., 276.01517616,
        276.19939829, 276.3609391 ]),
 array([288.52877231, 286.47856717, 286.84006063, ..., 281.93480223,
        282.14823869, 282.33386432]),
 array([290.78142724, 289.73905305, 289.93042715, ..., 281.70827135,
        281.95727214, 282.17475378]),
 array([295.04709088, 293.20661672, 293.53551207, ..., 287.16616237,
        287.40143432, 287.60484852]),
 array([286.89258101, 283.86961525, 284.40427888, ..., 284.19173599,
        284.34480541, 284.47659138]),
 array([293.59976529, 290.22257918, 290.78884033, ..., 288.61168806,
        288.85028327, 289.05555237]),
 array([294.97924465, 293.15176589, 293.46541694, ..., 286.04131731,
        286.31243252, 286.5479926 ]),
 array([305.37807313, 302.5614879 , 303.03412615, ..., 295.57253988,
        295.90703756, 296.19566974]),
 array([296.23536545, 293.64904513, 2